### ISSUE TITLE
Version of OpenCV of this code?

### ISSUE THREAD

**Issue by LeileiCao** [fengju514/Face-Pose-Net#23]
Hi, I run your code, but I got the error, I post here, would you please help me? Thank you very much, I appreciate.
The OpenCV version is 3.4.0 in my machine. The error shows as follows:
OpenCV Error: Assertion failed (dst.cols < 32767 && dst.rows < 32767 && src.cols < 32767 && src.rows < 32767) in remap, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 1749
Traceback (most recent call last):
  File "main_fpn.py", line 50, in <module>
    renderer_fpn.render_fpn(outpu_proc, output_pose_db, output_render)
  File "/home1/caoleilei/faceRec/Face-Pose-Net/renderer_fpn.py", line 88, in render_fpn
    model3D.ref_U, eyemask, model3D.facemask, opts)
  File "/home1/caoleilei/faceRec/Face-Pose-Net/face_renderer/renderer.py", line 109, in render
    frontal_raw = warpImg(img, ref_U.shape[0], ref_U.shape[1], prj_jnt, ind_jnt)
  File "/home1/caoleilei/faceRec/Face-Pose-Net/face_renderer/renderer.py", line 25, in warpImg
    np.squeeze( np.asarray( prj[1,:] ) ).astype('float32'),  cv2.INTER_CUBIC)
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:1749: error: (-215) dst.cols < 32767 && dst.rows < 32767 && src.cols < 32767 && src.rows < 32767 in function remap

**Comment by iacopomasi** [comment]
Hi,
the error is in the renderer, in the image warping function. We never tried with opencv 3.4. Can you try also with 2.0? Also, what is the size of the input image?

**Comment by LeileiCao** [comment]
I didn't try with OpenCV 2.0. The error indicated there was something wrong with the "cv2.remap" function. I guess it was caused by the difference between OpenCV 2.0 and 3.4. And I modified the input parameters of cv2.remap function as following: cv2.remap(img, np.squeeze( np.asarray( prj[0,:] ) ).astype('float32'), np.squeeze( np.asarray( prj[1,:] ) ).astype('float32'), cv2.INTER_CUBIC, borderMode=cv2.BORDER_CONSTANT, borderValue=0). 
But the error still occurs:
File "/home1/caoleilei/faceRec/Face-Pose-Net/face_renderer/renderer.py", line 26, in warpImg
    cv2.INTER_CUBIC,borderMode=cv2.BORDER_CONSTANT,borderValue=0)
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:1749: error: (-215) dst.cols < 32767 && dst.rows < 32767 && src.cols < 32767 && src.rows < 32767 in function remap.
The input file was just 'input.csv'， I didn't change anything.

**Comment by LeileiCao** [comment]
We have solved this issue. The problem is caused by the assertion of "cv2.remap"  function. This function in OpenCV 3 added the assertion if the cols or rows of map_x or map_y are larger than 32760. Unfortunately, the lengths of prj[0,:] and prj[1,:] are lager than 32767. We  divided the length into two parts to get remap, and then merge them.

**Comment by 1700117HLT** [comment]
Hi,LeileiCao ,I have the same issue about  "cv2.remap",how to divided the length into two parts to get remap?

**Comment by 1700117HLT** [comment]
I try
 pixels = cv2.remap(img, np.squeeze( np.asarray( prj[0,:] ) ).astype('float32').reshape(t_height, t_width),np.squeeze( np.asarray( prj[1,:] ) ).astype('float32').reshape(t_height, t_width), cv2.INTER_CUBIC)
        pixels = pixels.reshape(pixels.shape[0]*pixels.shape[1], pixels.shape[2])
I have solved this issue

**Comment by ileniTudor** [comment]
> I try
> pixels = cv2.remap(img, np.squeeze( np.asarray( prj[0,:] ) ).astype('float32').reshape(t_height, t_width),np.squeeze( np.asarray( prj[1,:] ) ).astype('float32').reshape(t_height, t_width), cv2.INTER_CUBIC)
> pixels = pixels.reshape(pixels.shape[0]*pixels.shape[1], pixels.shape[2])
> I have solved this issue

thank you !!solve the problem. 
In case of:
background = yes (face_renderer/config.ini) we do not need  the reshape(t_height, t_width) part

**Comment by Symbiomatrix** [comment]
Kudos for the fix. I've incorporated it in my fork.
