### ISSUE TITLE
lmdb.Error: ./output_pose.lmdb: There is not enough space on the disk.

### ISSUE THREAD

**Issue by ihmc3jn09hk** [fengju514/Face-Pose-Net#25]
Hello Feng,
        I tried to run the code and the following issue came out. Do I knew more RAM on this code???

`Traceback (most recent call last):
  File "main_fpn.py", line 48, in <module>
    getRts.esimatePose( model_folder, outpu_proc, output_pose_db, model_used, lr_rate_scalar, if_dropout, keep_rate, use_gpu=True )
  File "F:\PROJECTS\Face Reconstruction\Face-Pose-Net-master\get_Rts.py", line 121, in esimatePose
    run_pose_estimation( root_model_path, inputFile, outputDB, model_used, lr_rate_scalar, if_dropout, keep_rate )
  File "F:\PROJECTS\Face Reconstruction\Face-Pose-Net-master\get_Rts.py", line 61, in run_pose_estimation
    pose_lmdb_env = lmdb.Environment(outputDB, map_size=1e12)
lmdb.Error: ./output_pose.lmdb: There is not enough space on the disk.`

**Comment by Symbiomatrix** [comment]
It seems that lmdb on windows (at least that's where I've encountered it) creates a file of precisely the requested storage capacity, rather than as a maximum. It's defined in the code to be 1e12 (1TB). I've reduced it to 1e9 (1GB) in my fork as recommended on SOF, with no apparent adverse effects.
